---
name: Build and push image to GCP
on:
  push:
    branches: [master]

jobs:
  build-push-gcp:
    name: Build and push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dmedico-server
      PROJECT_ID: ecomscraper
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run:  docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run:  |-        
        gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    - name: Push container image to Artifactory Registry      
      run: |-
        docker tag $IMAGE_NAME:latest asia-south1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest        
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
